### ISSUE TITLE
cannot get feed, connection refused

### ISSUE THREAD

**Issue by bilalbayasut** [Brandawg93/homebridge-ezviz#21]
**Describe the bug**
couldn't get camera feed

**Debug Output**
```
[EZVIZ] Error: Command failed with exit code 1: /homebridge/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://xxx:XXXXX@0.0.0.0/Streaming/Channels/1/ -vframes 1 -f mjpeg -
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0xaaaae986c6d0] Connection to tcp://0.0.0.0:554?timeout=0 failed: Connection refused
rtsp://xxx:XXXXX@0.0.0.0/Streaming/Channels/1/: Connection refused

    at makeError (/homebridge/node_modules/homebridge-ezviz/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/homebridge/node_modules/homebridge-ezviz/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 1: /homebridge/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://xxx:XXXXX@0.0.0.0/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  command: '/homebridge/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://xxx:XXXXX@0.0.0.0/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  escapedCommand: '"/homebridge/node_modules/homebridge-ezviz/node_modules/ffmpeg-for-homebridge/ffmpeg" -i "rtsp://xxx:XXXXX@0.0.0.0/Streaming/Channels/1/" -vframes 1 -f mjpeg -',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 33 2e 31 20 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 32 30 30 30 2d 32 30 32 30 20 74 68 65 20 46 ... 1339 more bytes>,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**To Reproduce**
previously ran fine, and suddenly connection refused, though I've restarted it

1. -

**Expected behavior**
feed run fine without error

Please answer these questions before submitting this issue:
```
On what device are you running homebridge:  rasppberry pi 3
On what iOS version are you having issues: iOS 14.6
What camera types are having issues: E19005273
Does this issue occur consistently or randomly: randomly
If applicable, what was the last version that worked properly: 
```
Cache cleared and restarted the home ridge container , but error still persist

**Comment by bilalbayasut** [comment]
nvm , fixed by rebooting the camera
