### ISSUE TITLE
Homebridge cannot connect to my C3X camera

### ISSUE THREAD

**Issue by lucj** [Brandawg93/homebridge-ezviz#64]
**Describe the bug**

I've installed and configured the plugin but it seems HomeBridge cannot connect to the camera. 

**Debug Output**

[29/05/2022, 22:47:21] [EZVIZ] Error: Command failed with exit code 1: /var/lib/homebridge/node_modules/.pnpm/ffmpeg-for-homebridge@0.0.9/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:XXX@192.x.y.z/Streaming/Channels/1/ -vframes 1 -f mjpeg -
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[rtsp @ 0x2535260] method DESCRIBE failed: 401 Unauthorized
rtsp://admin:XXX@192.x.y.z/Streaming/Channels/1/: Server returned 401 Unauthorized (authorization failed)
    at makeError (/var/lib/homebridge/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/var/lib/homebridge/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: /var/lib/homebridge/node_modules/.pnpm/ffmpeg-for-homebridge@0.0.9/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:XXX@192.x.y.z/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  command: '/var/lib/homebridge/node_modules/.pnpm/ffmpeg-for-homebridge@0.0.9/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://admin:XXX@192.x.y.z/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  escapedCommand: '"/var/lib/homebridge/node_modules/.pnpm/ffmpeg-for-homebridge@0.0.9/node_modules/ffmpeg-for-homebridge/ffmpeg" -i "rtsp://admin:XXX@192.x.y.z/Streaming/Channels/1/" -vframes 1 -f mjpeg -',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 35 2e 30 20 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 32 30 30 30 2d 32 30 32 32 20 74 68 65 20 46 46 6d ... 1394 more bytes>,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
[29/05/2022, 22:47:30] [EZVIZ] Streaming started for C3X
[29/05/2022, 22:47:30] [EZVIZ] STREAM: STREAM: rtsp://admin:XXX@192.x.y.z/Streaming/Channels/1/: Server returned 401 Unauthorized (authorization failed)
[29/05/2022, 22:47:30] [EZVIZ] Streaming stopped for C3X

**To Reproduce**

1. Add and configure plugin

**Expected behavior**

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: 

Raspberry PI 4

On what iOS version are you having issues: 

15.4.1

What camera types are having issues: 

C3X

Does this issue occur consistently or randomly: 

consistently

If applicable, what was the last version that worked properly: 
```

**Comment by lucj** [comment]
My fault, was using password instead of camera verification code... :(
