### ISSUE TITLE
Cannot Connect to All cam in the account

### ISSUE THREAD

**Issue by acebugner** [Brandawg93/homebridge-ezviz#92]
This is an example of one of the cam when I click on it on homekit app.
[7/2/2023, 8:39:21 PM] [EZVIZ] Error: Command failed with exit code 1: ffmpeg -i rtsp://admin:VFPVKP@192.168.252.110/Streaming/Channels/1/ -vframes 1 -f mjpeg -
ffmpeg version 4.1.8 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8.5.0 (GCC)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=arm64 --target-os=linux --cross-prefix=/usr/local/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --disable-stripping --enable-version3 --enable-encoders --enable-pthreads --disable-protocols --disable-protocol=rtp --enable-protocol=file --enable-protocol=pipe --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffplay --disable-ffprobe --disable-doc --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-cuvid --disable-nvenc --disable-decoder=aac --disable-decoder=aac_fixed --disable-encoder=aac --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-decoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=eac3 --disable-encoder=truehd --disable-decoder=truehd --disable-encoder=hevc_vaapi --disable-decoder=hevc --disable-muxer=hevc --disable-demuxer=hevc --disable-parser=hevc --disable-bsf=hevc_mp4toannexb --x86asmexe=yasm --cc=/usr/local/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-wrap-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
rtsp://admin:VFPVKP@192.168.252.110/Streaming/Channels/1/: Protocol not found
Did you mean file:rtsp://admin:VFPVKP@192.168.252.110/Streaming/Channels/1/?

    at makeError (/volume1/homebridge/node_modules/homebridge-ezviz/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/volume1/homebridge/node_modules/homebridge-ezviz/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: ffmpeg -i rtsp://admin:VFPVKP@192.168.252.110/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  command: 'ffmpeg -i rtsp://admin:VFPVKP@192.168.252.110/Streaming/Channels/1/ -vframes 1 -f mjpeg -',
  escapedCommand: 'ffmpeg -i "rtsp://admin:VFPVKP@192.168.252.110/Streaming/Channels/1/" -vframes 1 -f mjpeg -',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 31 2e 38 20 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 32 30 30 30 2d 32 30 32 31 20 74 68 65 20 46 ... 1936 more bytes>,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Describe the bug**
Cannot see video on any cam on the account

**Debug Output**
Above

**To Reproduce**
Click on the cam on home app

1. 

**Expected behavior**
Show image.

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Synology
On what iOS version are you having issues: 16.5.1
What camera types are having issues: C3A
Does this issue occur consistently or randomly: consistent;y
If applicable, what was the last version that worked properly: 
Never worked.
```

**Comment by dpamping** [comment]
maybe DP1C doorbelll is not supported? Im getting this message: 
STREAM: STREAM: rtsp://admin:FPXSHT@192.168.68.151/Streaming/Channels/1/: Connection refused

ERROR[Ezviz Bridge D39A@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'DP1CE44642232' was slow to respond!

**Comment by acebugner** [comment]
This is not a doorbell it is Ezviz C3A cam.
